"""
strategies/ — Strategy Engine Package

All strategies implement generate_signals() returning a list of Signal objects.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    direction: str          # "long", "short", or "cash"
    strength: float         # 0.0 to 1.0, how confident
    strategy: str           # name of the strategy that generated it
    timestamp: datetime = field(default_factory=datetime.now)

    def __repr__(self):
        return f"Signal({self.symbol} {self.direction} str={self.strength:.2f} via {self.strategy})"
